### ISSUE TITLE
Add Manga element?

### ISSUE THREAD

**Issue by bpepple** [Metron-Project/metroninfo#2]
Requires the possible following information:

- status (Unknown, True, False)
- reading direction (Right->Left; Left->Right)

**Comment by bpepple** [comment]
Is this something we really want? Or should manga have their own format?

**Comment by majora2007** [comment]
Chiming in here as Manga is a big focus for me. I don't really think reading information needs to be stored in the format, but I do think the format should allow for Manga information. 

For example, alternative titles, different roles for people (not having to re-map to Penciller for example), and Format status like Omnibus. I think having a separate format would really drive down adoption.

**Comment by bpepple** [comment]
> Chiming in here as Manga is a big focus for me. I don't really think reading information needs to be stored in the format, but I do think the format should allow for Manga information.
> 
> For example, alternative titles, different roles for people (not having to re-map to Penciller for example), and Format status like Omnibus. I think having a separate format would really drive down adoption.

@majora2007: I agree having a separate format would drive down potential adoption. My knowledge of manga is fairly basic and most of the folks that have helped out also aren't really manga readers, so any input from people knowledgeable about manga would be greatly appreciated!

Regarding your suggestions, I've a few questions:

- **Alternative titles** - What information would this contain? Alternative name for the series? Or something else? Also, would this contain multiple values and necessitate having children elements?
- **Creator Roles** - What values would need to be added? Here's what's currently define: [Roles](https://github.com/Metron-Project/metroninfo/blob/349355e39e9a6bc6b0fbaff9a6aeb388fd452ae0/drafts/v1.0/MetronInfo.xsd#L248)
- **Omnibus** - Isn't the primary difference between an Trade Paperback and an Omnibus, the number of issues reprinted within them? Or do they have a different meaning for Manga?

I'm not opposed to adding support for Manga, but like I said above, my own knowledge about Manga is fairly limited, so I definitely shouldn't be the one making the final decision on what's needed.

Also, it would be beneficial to get your thoughts on what you'd like to see included in the format as someone writing a comic server, since it's a different viewpoint from where I'm coming from as someone working a comic book database.

**Comment by majora2007** [comment]
> Alternative titles - What information would this contain? Alternative name for the series? Or something else? Also, would this contain multiple values and necessitate having children elements?

From my personal experience, these are alternative names for the series. At a minimum, you just need a list of alternative strings to match against, however, taking a step further an attribute for the language code might also be beneficial. However, there may be more than one alternative title per language code. 

See: 
https://anilist.co/manga/122063/ShangriLa-Frontier-Kusoge-Hunter-Kami-ge-ni-Idoman-to-su/
There are multiple Synonyms attached to this, some in japanese, most in romanji. 

> Creator Roles - What values would need to be added?
You have a much better set than ComicInfo. I don't think any changes are needed.  

> Omnibus - Isn't the primary difference between an Trade Paperback and an Omnibus, the number of issues reprinted within them? Or do they have a different meaning for Manga?
Yes they are different. An Omnibus is a collection of Volumes into 1 file. So You may have a series re-released as Omnibus where 2 volumes are released as a new Volume number. So a series of 4 volumes is now just Volume 1 and 2 (containing 1-2 and 3-4 respectively). 

TPBs combine issues that make up a story arc. 

From my perspective, there are a few more things that might be nice to capture as optional fields but I'm not 100% sold they are needed. The problem arises from Series-level vs Issue-level metadata. All server's inherit series-level metadata from the first issue. 

Since series-level metadata is needed, here's my wishlist:
- In addition to `Count` which is used to derive publication status, a `PublicationStatus` field which has values "Ongoing", "Cancelled", "Complete", "Hiatus", etc. For comics, I believe they only have Complete or Ongoing, but mangas can be cancelled or on Hiatus (indefinitely). 
- Metadata ids (I believe you already have this solved and it's flexible for other sites)
- Formal documentation around Issue number and Volume number (like how to handle ranges, special characters, etc)

**Comment by bpepple** [comment]
> > Alternative titles - What information would this contain? Alternative name for the series? Or something else? Also, would this contain multiple values and necessitate having children elements?
> 
> From my personal experience, these are alternative names for the series. At a minimum, you just need a list of alternative strings to match against, however, taking a step further an attribute for the language code might also be beneficial. However, there may be more than one alternative title per language code.
> 
> See: https://anilist.co/manga/122063/ShangriLa-Frontier-Kusoge-Hunter-Kami-ge-ni-Idoman-to-su/ There are multiple Synonyms attached to this, some in japanese, most in romanji.
> 
So, would something like this work? (Not sure the `id` attribute is needed, but doesn't hurt to have the option):
```
    <Series id="65478" lang="en">
        <Name>Justice League</Name>
        <SortName>Justice League</SortName>
        <Volume>2</Volume>
        <Format>Series</Format>
        <AlternativeNames>
           <Name id="1234" lang="en">Foo</Name>
           <Name id="5689" lang="de">Hüsker Dü</Name> 
        </AlternativeNames>
    </Series>
```
Or is their some another solution that would work better?

> Omnibus - Isn't the primary difference between an Trade Paperback and an Omnibus, the number of issues reprinted within them? Or do they have a different meaning for Manga?
> 
> > Yes they are different. An Omnibus is a collection of Volumes into 1 file. So You may have a series re-released as Omnibus where 2 volumes are released as a new Volume number. So a series of 4 volumes is now just Volume 1 and 2 (containing 1-2 and 3-4 respectively).
> > 
> > TPBs combine issues that make up a story arc.
> > 
Ok, sounds like it would be worthwhile to add **Omnibus** to the `formatType` then.

> From my perspective, there are a few more things that might be nice to capture as optional fields but I'm not 100% sold they are needed. The problem arises from Series-level vs Issue-level metadata. All server's inherit series-level metadata from the first issue.
> 
> Since series-level metadata is needed, here's my wishlist:
> 
>  In addition to `Count` which is used to derive publication status, a `PublicationStatus` field which has values "Ongoing", "Cancelled", "Complete", "Hiatus", etc. For comics, I believe they only have Complete or Ongoing, but mangas can be cancelled or on Hiatus (indefinitely).
> 
What is the `Count`? The number of issues in a series or limited series? If so, I'm not 100% it would be a worthwhile field to add since it's value could potentially differ per issue per series based on when they are tagged.

Also, I agree adding a `PublicationStatus` field is a pretty good idea.

> 
>     * Formal documentation around Issue number and Volume number (like how to handle ranges, special characters, etc)

I agree, any suggestion on what to add/change would be appreciated.

**Comment by bpepple** [comment]
Ok, I added an `AlternativeNames` sub-element to the `Series` element, and added `Omnibus` to format type.

Regarding, the **Count** and **Series Status**, I've decided to table those for now, since the general consensus seems to be that elements since Series-level information like that changes. I've opened a bug #38 to track these if in the future we want to revisit this.
