### ISSUE TITLE
Age Ratings

### ISSUE THREAD

**Issue by majora2007** [Metron-Project/metroninfo#47]
The current spec offers a drastically reduced Age Rating setup than what is current in ComicInfo. ComicInfo went the opposite way of bringing every potential age rating. We need to meet in the middle. 

Currently Age Rating is used primarily in reading servers as a way to gate access to different media for age restricted accounts (kids, grandma, etc). 

I'm opening this to propose a few more Ratings to allow for flexibility, especially when you adapt this to Manga.

```
<xs:enumeration value="Unknown" />
<xs:enumeration value="Everyone" /> <!-- Appropriate for readers of all ages. -->
<xs:enumeration value="Teen" /> <!-- Appropriate for readers age 12 and older. -->
<xs:enumeration value="Teen Plus" /> <!-- Appropriate for readers age 15 and older. -->
<xs:enumeration value="Mature" /> <!-- Appropriate for readers age 17 and older. -->
```

I believe we need an `Explicit` and potentially one more above that that, like how NC-17 exists beyond R. 

Update: Based on community suggestions, we will have the following:

```
<xs:enumeration value="Unknown" />
<xs:enumeration value="Everyone" /> <!-- Appropriate for readers of all ages. -->
<xs:enumeration value="Teen" /> <!-- Appropriate for readers age 12 and older. -->
<xs:enumeration value="Teen Plus" /> <!-- Appropriate for readers age 15 and older. -->
<xs:enumeration value="Mature" /> <!-- Appropriate for readers age 17 and older. -->
<xs:enumeration value="Explicit" /> <!-- Contains Gore, Sexually Explicit material that would be more extreme than R rating -->
<xs:enumeration value="Adult" /> <!-- Likely pornographic in nature -->
```

**Comment by bpepple** [comment]
I've been giving this some thought, and I think part of the issue is we are referring/using this as two different types of information.

I've been thinking of this as a field that is used to track the rating of a comic that is assigned by the **Publisher**, and I believe you (Joe) are thinking of this field as a way to tracking the rating given to it from the **User**.

Maybe we should be split into two elements to track these separate pieces of information.

**Comment by Cducharme84** [comment]
I think a large part of the need for an "Adult" or "Explicit" designation is actually derived from publisher practices, for example bagging the titles that are so "Mature" the covers themselves aren't able to be displayed in some markets they sell in. 

So while the publisher will mark a bagged "Mature" book and a gory but unbagged "Mature" book as the same rating they're clearly creating a differentiation we cannot achieve digitally without accommodation of what is indeed essentially a user designation that mimics the bagging process and allows reading softwares to automate the "bagging" or restriction to this material.

I am definitely agreed that a step above Mature makes sense, and it also makes sense DC didn't create one with their aversion to mature storylines in general and more explicit storylines being completely against their own policy. We can't exactly rely on DC style rating for say Avatar Press, London Night Studios, Eros, Eurotica, and honestly countless of the "comix" scene publisher's books as DC has never even attempted to service the market base for those genres.

**Comment by aaronleopold** [comment]
Hey :wave: just wanted to pop in and say +1 to adding more ratings, I think an `Explicit` plus one (whatever they might be named) is ideal and covers a good range without supporting the world's preferences for representing age rating.

> Maybe we should be split into two elements to track these separate pieces of information

I don't personally see these as separate fields, I think it's valid for a user to change the rating assigned by the publisher without constituting a separate field. I don't think there is a meaningful difference between what I understand to just be a default rating (the publisher says it's this) and what a user would rate it (effectively an override). Unless it is really important to distinguish between the two and/or retain the original rating? I could be wrong, just my two cents 🙂

**Comment by therobbiedavis** [comment]
I agree that there needs to be a step above mature as well for those depicting nudity or otherwise NSFW subject matter that is more explicit than gore or violence.

As far as the ratings themselves I think Metron itself can have it's own age ratings, however from a ingestion/reader service I think there needs to be some sort of mapping system similar to XEM that Sonarr uses to map episode numbering (https://thexem.info/xem/show/5624).

The idea is for this external system (independent of Kavita or Metron) to provide a matrix mapping mechanism that will allow mapping to a standardized set of ratings regardless of the source data.

Below is an example:
| DC (2011-2022) Rating | DC (2022-) Rating | Marvel (2005-) Rating | Tokyopop Rating      | Seven Seas Rating | Viz Rating       | ComicInfo Rating          | Metron Rating |
|-----------------------|-------------------|-----------------------|----------------------|-------------------|------------------|---------------------------|---------------|
| M - Mature            | 17+               | Parental Advisory     | OT - Older Teens 16+ | Older Teen 17+    | Older Teen (16+) | Mature 17+ M              | Mature        |
|                       |                   | Explicit Content      | M - Mature 18+       | Mature 18+        | Mature (18+)     | Adults Only 18+ R18+ X18+ | Explicit      |
|                       |                   |                       |                      |                   |                  |                           |               |

**Comment by ElryGH** [comment]
Mature & Explicit are definitely needed

**Comment by bpepple** [comment]
> As far as the ratings themselves I think Metron itself can have it's own age ratings, however from a ingestion/reader service I think there needs to be some sort of mapping system similar to XEM that Sonarr uses to map episode numbering (https://thexem.info/xem/show/5624).

That has been planned for a long time, just haven't had time to add it to the documentation.

**Comment by bpepple** [comment]
@majora2007 Has there been a consensus on what your users want for the Age Rating values?

I started writing a [PR](https://github.com/Metron-Project/metron-project.github.io/pull/9) for an Age Rating matrix for the documentation, which will obviously need to be updated based on the decision made in the bug.

**Comment by majora2007** [comment]
Yes, the consensus is to include 2 more (I updated my original post with this info)

```
<xs:enumeration value="Unknown" />
<xs:enumeration value="Everyone" /> <!-- Appropriate for readers of all ages. -->
<xs:enumeration value="Teen" /> <!-- Appropriate for readers age 12 and older. -->
<xs:enumeration value="Teen Plus" /> <!-- Appropriate for readers age 15 and older. -->
<xs:enumeration value="Mature" /> <!-- Appropriate for readers age 17 and older. -->
<xs:enumeration value="Explicit" /> <!-- Contains Gore, Sexually Explicit material that would be more extreme than R rating -->
<xs:enumeration value="Adult" /> <!-- Likely pornographic in nature -->
```

**Comment by bpepple** [comment]
> Yes, the consensus is to include 2 more (I updated my original post with this info)
> 
> ```
> <xs:enumeration value="Unknown" />
> <xs:enumeration value="Everyone" /> 
> <xs:enumeration value="Teen" /> 
> <xs:enumeration value="Teen Plus" /> 
> <xs:enumeration value="Mature" /> 
> <xs:enumeration value="Explicit" /> 
> <xs:enumeration value="Adult" /> 
> ```

Ah, didn't get a notification that you updated your previous comment. Anyway, I'll work up a PR at lunch for this change, and I'll tag you for a review.
